kind: pipeline
type: kubernetes
name: default
metadata:
  namespace: git
concurrency:
  limit: 1
volumes:
  - name: cache
    claim:
      name: storage2
steps:
  - name: build
    image: docker
    privileged: true
    volumes:
      - name: cache
        path: /cache
    environment:
      TOKEN:
        from_secret: gitea
      TOKEN_DOCKER:
        from_secret: docker_hub
    commands:
      - dockerd --data-root /cache/dockerd &
      - docker login -u voidic -p $TOKEN_DOCKER
      - docker buildx build --push -t voidic/dtan-server:latest .
      - kill $(cat /var/run/docker.pid)